@startuml
title API Tennis Project Structure

package "Main Program" {
    [main.py]
}

package "Config & API" {
    [config.py]
}

package "Features" {
    [weather.py]
    [rankings.py]
    [search.py]
    [tournaments.py]
}

[main.py] --> [weather.py]
[main.py] --> [rankings.py]
[main.py] --> [config.py]
[main.py] --> [tournaments.py]
[main.py] --> [search.py]

[weather.py] --> [config.py]
[rankings.py] --> [config.py]
[search.py] --> [config.py]
[tournaments.py] --> [config.py]
@enduml
